version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10.11

    steps:
      - run:
          name: Update package lists
          command: apt-get update

      - run:
          name: Install MTDev
          command: apt-get install -y libmtdev-dev

      - run:
          name: Install system dependencies
          command: |
            apt-get install -y libgl1-mesa-glx xvfb

      - run:
          name: Configure virtual display
          command: Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
          background: true

      - run:
          name: Set display environment variable
          command: export DISPLAY=:99

      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            # pip install -r requirements-dev.txt

      - run:
          name: Run black
          command: |
            black --config=pyproject.toml .

      - run:
          name: Run flake8
          command: |
            flake8 --config=setup.cfg

      - run:
          name: Run isort
          command: |
            isort --profile=black .

      - run:
          name: Run pytype
          command: |
            pytype .
