version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd litespace/backend
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - run:
          name: Run black
          command: |
            cd litespace/backend
            black .

      - run:
          name: Run flake8
          command: |
            cd litespace/backend
            flake8

      - run:
          name: Run isort
          command: |
            cd litespace/backend
            isort .

